export const home_md = `
---
# **Welcome to Our User Study on Sketching Narrative Structures!**

# Consent Form
## Invitation to Participate in the Study
You are invited to participate in a study titled "Sketching Narrative Structures". This study is being conducted by the Department of Human Centred Computing, Monash University. 
Please read through this explanatory statement before deciding whether to participate. If you require further information regarding any aspect of this project, you are encouraged to contact the researchers via the email addresses provided.
## Project Details
**Project ID:** 36056

**Project Title:** Sketching Narrative Structures

**Student Investigator:** 
   - Songhai Fan (songhai.fan@monash.edu)


**Co-Investigators:** 
   - Dr. Ying Yang (ying.yang@monash.edu), 
   - Professor Tim Dwyer (tim.dwyer@monash.edu),
   - Professor Helen Purchase (helen.purchase@monash.edu)
   - Assoc Professor Simon Angus (simon.angus@monash.edu)

## What Does the Research Involve?
This study aims to investigate the influence of textual and graphic narrative structures on the understanding and interpretation of news stories. We will use datasets generated by Large Language Models (LLMs) with predefined narrative structures to explore the effectiveness and comprehension of news structures.
If you choose to participate, you will be asked to:

   - [ ] Provide a Prolific ID
   - [ ] Participate in a user study involving visualisations and narrative structures
   - [ ] Finish task and answer questions based on the text or visualisation
   - [ ] Complete a survey

Your participation is entirely voluntary and you may choose to withdraw at any stage without any implications.
## Why Were You Chosen for this Research?
You have been invited to participate in this research because your experience and opinions are valuable to our study. 


## Confidentiality and Data Storage
The confidentiality of your data is a priority. Any personally identifiable information will not be shared with anyone not involved in this project. All data collected will be stored securely and will be retained for five years after the completion of the study.

## Payment
As a token of gratitude, we offer a payment of €15 per hour upon completion of the study. The payment will be processed manually and transferred to your Prolific.co account.

## Complaints

Should you have any concerns or complaints about the conduct of the project, you are welcome to contact the Executive Officer, Monash University Human Research Ethics (MUHREC) at muhrec@monash.edu or +61 3 9905 2052.

---
`;

export const about_md = `
---
# TT-Graphs: An Introduction
In our study, we introduce the concept of TT-graphs, or Theme-Time graphs, as a method of visually representing narrative structures. 
Imagine a grid - like a chess board or a spreadsheet. In a TT-Graph, or Theme-Time graph, nodes are plotted on a grid. This grid is essentially a matrix, with each cell representing a node. The position of a node on the grid is determined by two coordinates: the x-coordinate and the y-coordinate.

The x-coordinate (horizontal axis) represents time. It's like a timeline that shows when things happen in the story. As you move from left to right along the x-axis, you're moving forward in time.

The y-coordinate (vertical axis) represents different themes in the story. Each row on the y-axis corresponds to a different theme. So, if a node is in the third row, for example, that means it's part of the third theme.

The color of each node is used to represent its theme. Each theme is assigned a different color. So, all the nodes that are part of the same theme will be the same color. This makes it easy to see at a glance which parts of the story are about which themes.

For example, if you see a lot of blue nodes on the left side of the graph and a lot of red nodes on the right side, that means the story started out focusing on the blue theme and then shifted to focus on the red theme.

By looking at the positions and colors of the nodes, you can get a sense of how the story's themes evolve over time. This can help you understand the structure of the story and how different themes are interconnected.

## Characteristics
- **One-way Paths**: The lines or paths (called edges) in TT-graphs can only go from left to right, like reading a book.
- **Row Swapping**: Two TT-graphs are considered the same if you can get from one to the other by just swapping rows around.
- **No Empty Timeframes**: If a column (which represents a certain timeframe) doesn't have any nodes, then all the columns to its right should also be empty.

## Narrative Motifs in TT-Graphs

Given the restrictions and structure of the TT-graph, the minimal motifs that can be observed are:
1. **SingleThemeEvolution(retain)**: 
   This motif consists of a series of directed edges representing the evolution or continuation of a single theme through time.
2. **SingleStepForward(shift)**:
   This motif represents a shift from one theme to another over a single time step.

## Use in Research

In our research, we use TT-graphs to explore the influence of textual and graphic narrative structures on the understanding and interpretation of news stories. TT-graphs serve as a valuable tool for visually communicating narratives and facilitating comparative studies of textual and graphic.

---
`;

export const more_md = `
---
Thank you for participating. Your contribution will play a pivotal role in exploring the underlying narratives of news stories. 🌍✍
---
`;
