export const home_md = `
---
# **Welcome to Our User Study on Sketching Narrative Structures!**

# Consent Form
## Invitation to Participate in the Study
You are invited to participate in a study titled "Sketching Narrative Structures". This study is being conducted by the Department of Human Centred Computing, Monash University. 
Please read through this explanatory statement before deciding whether to participate. If you require further information regarding any aspect of this project, you are encouraged to contact the researchers via the email addresses provided.
## Project Details
**Project ID:** 36056

**Project Title:** Sketching Narrative Structures

**Student Investigator:** 
   - Songhai Fan (songhai.fan@monash.edu)


**Co-Investigators:** 
   - Dr. Ying Yang (ying.yang@monash.edu), 
   - Professor Tim Dwyer (tim.dwyer@monash.edu),
   - Professor Helen Purchase (helen.purchase@monash.edu)
   - Assoc Professor Simon Angus (simon.angus@monash.edu)

## What Does the Research Involve?
This study aims to investigate the influence of textual and graphic narrative structures on the understanding and interpretation of news stories. We will use datasets generated by Large Language Models (LLMs) with predefined narrative structures to explore the effectiveness and comprehension of news structures.
If you choose to participate, you will be asked to:

   - [ ] Provide a Prolific ID
   - [ ] Participate in a user study involving visualisations and narrative structures
   - [ ] Finish task and answer questions based on the text or visualisation
   - [ ] Complete a survey

Your participation is entirely voluntary and you may choose to withdraw at any stage without any implications.
## Why Were You Chosen for this Research?
You have been invited to participate in this research because your experience and opinions are valuable to our study. 


## Confidentiality and Data Storage
The confidentiality of your data is a priority. Any personally identifiable information will not be shared with anyone not involved in this project. All data collected will be stored securely and will be retained for five years after the completion of the study.

## Payment
As a token of gratitude, we offer a payment of €15 per hour upon completion of the study. The payment will be processed manually and transferred to your Prolific.co account.

## Complaints

Should you have any concerns or complaints about the conduct of the project, you are welcome to contact the Executive Officer, Monash University Human Research Ethics (MUHREC) at muhrec@monash.edu or +61 3 9905 2052.

---
`;

export const about_md = `
---
# TT-Graphs: An Introduction
In our study, we introduce the concept of Theme-Time graphs (TT-graphs), as a method of visually representing narrative structures. Imagine a grid like a chess board or a spreadsheet. In a TT-Graph, nodes representing story chapters are plotted on a grid. The position of a node on the grid is determined by two coordinates: the x-coordinate and the y-coordinate.


![Concept](https://raw.githubusercontent.com/SonghaiFan/user_study_narrative_sketch/gh-pages/concept.png)

The x-coordinate (horizontal axis) represents time. It's like a timeline that shows when things happen in the story. As you move from left to right along the x-axis, you're moving forward in time. Thus, each column represents a distinct timeframe.

The y-coordinate (vertical axis) represents different themes in the story. Each row on the y-axis corresponds to a different theme. So, if a node is in the third row, for example, that means it's part of the third theme.

The colour of each node also represents its theme. Each theme is assigned a different colour so that all the nodes that are part of the same theme will be the same colour. This makes it easy to see at a glance which parts of the story are about which themes.

By looking at the positions and colours of the nodes, you can get a sense of how the story's themes evolve over time. This can help you understand the structure of the story and how different themes are interconnected.

Links between nodes indicate that those chapters discuss common themes or entities (people, places, organisations) discussed. In the short stories we present in TT-graphs in this study, a path connects all chapters across timeframes.


## Characteristics
- **One-way Paths**: The lines in TT-graphs can only go from left to right, like reading a book.

- **Row Swapping**: Two TT-graphs are considered the same if you can get from one to the other by just swapping rows around.

- **No Empty Timeframes Gap**: Columns (which represent certain timeframes) cannot have an empty column between them. For instance, if we think of the columns as "Past", "Present", and "Future", we can't have nodes in "Past" and "Future" without anything in the "Present".


## Narrative Motifs in TT-Graphs

Narrative motifs in TT (Theme-Time) layout graphs are recurring patterns or structures that help to depict how themes evolve over time in a narrative. They are like the building blocks of a story, representing the simplest units of meaning within the narrative structure.

![Motifs](https://raw.githubusercontent.com/SonghaiFan/user_study_narrative_sketch/gh-pages/motifs.png)

1. **Linear**: Three chapters follow a single theme in a sequential order.
2. **Arch**: The narrative starts with one theme, shifts to another, then returns to the first theme.
3. **Ladder**: The narrative starts with one theme, then moves to a second theme, and ends with a third theme.
4. **LongFork**: The narrative follows one theme for two chapters, then shifts to a second theme for the final chapter.
5. **ShortFork**: The narrative follows one theme in the first chapter, then shifts to a second theme for the remaining chapters.
6. **WideMerge**: Two initial chapters follow different themes and converge into a shared theme in the last chapter.
7. **WideBranch**: The narrative starts with one theme and branches out to two different themes in the following chapters.
8. **SharpMerge**: Two chapters from different themes converge into a single theme in the last chapter.
9. **SharpBranch**: The narrative starts with one theme and diverges into two different themes in the later chapters.


## Use in Research

In our research, we use TT-graphs to explore the influence of textual and graphic narrative structures on the understanding and interpretation of news stories. TT-graphs serve as a valuable tool for visually communicating narratives and facilitating comparative studies of textual and graphic.

---
`;

export const end_md = `
---
Thank you for participating. Your contribution will play a pivotal role in exploring the underlying narratives of news stories. 🌍✍
---
`;
